package DistributedAuctionApp;


/**
* DistributedAuctionApp/DistributedAuctionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedAuctionApp.idl
* Sunday, March 11, 2018 9:34:59 PM CDT
*/

public interface DistributedAuctionOperations 
{
  boolean offerItem (String itemName, String userID, double startPrice) throws DistributedAuctionApp.DistributedAuctionPackage.IncorrectOfferException;
  String viewHighBidder (String userID) throws DistributedAuctionApp.DistributedAuctionPackage.IncorrectSellException;
  DistributedAuctionApp.DistributedAuctionPackage.AuctionStatus viewAuctionStatus (String userID) throws DistributedAuctionApp.DistributedAuctionPackage.IncorrectStatusException;
  String viewBidStatus (String userID) throws DistributedAuctionApp.DistributedAuctionPackage.IncorrectBidException;
  boolean bid (String userID, double price) throws DistributedAuctionApp.DistributedAuctionPackage.IncorrectBidException;
  boolean sell (String userID) throws DistributedAuctionApp.DistributedAuctionPackage.IncorrectSellException;
} // interface DistributedAuctionOperations
