package DistributedAuctionApp;


/**
* DistributedAuctionApp/DistributedAuction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedAuctionApp.idl
* Sunday, March 11, 2018 9:34:59 PM CDT
*/

public interface DistributedAuction extends DistributedAuctionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DistributedAuction
