package DistributedAuctionApp.DistributedAuctionPackage;

/**
* DistributedAuctionApp/DistributedAuctionPackage/AuctionStatusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedAuctionApp.idl
* Sunday, March 11, 2018 9:34:59 PM CDT
*/

public final class AuctionStatusHolder implements org.omg.CORBA.portable.Streamable
{
  public DistributedAuctionApp.DistributedAuctionPackage.AuctionStatus value = null;

  public AuctionStatusHolder ()
  {
  }

  public AuctionStatusHolder (DistributedAuctionApp.DistributedAuctionPackage.AuctionStatus initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DistributedAuctionApp.DistributedAuctionPackage.AuctionStatusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DistributedAuctionApp.DistributedAuctionPackage.AuctionStatusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DistributedAuctionApp.DistributedAuctionPackage.AuctionStatusHelper.type ();
  }

}
