package DistributedAuctionApp.DistributedAuctionPackage;


/**
* DistributedAuctionApp/DistributedAuctionPackage/AuctionStatusHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedAuctionApp.idl
* Sunday, March 11, 2018 9:34:59 PM CDT
*/

abstract public class AuctionStatusHelper
{
  private static String  _id = "IDL:DistributedAuctionApp/DistributedAuction/AuctionStatus:1.0";

  public static void insert (org.omg.CORBA.Any a, DistributedAuctionApp.DistributedAuctionPackage.AuctionStatus that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DistributedAuctionApp.DistributedAuctionPackage.AuctionStatus extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "userID",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "itemName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[2] = new org.omg.CORBA.StructMember (
            "bidPrice",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (DistributedAuctionApp.DistributedAuctionPackage.AuctionStatusHelper.id (), "AuctionStatus", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DistributedAuctionApp.DistributedAuctionPackage.AuctionStatus read (org.omg.CORBA.portable.InputStream istream)
  {
    DistributedAuctionApp.DistributedAuctionPackage.AuctionStatus value = new DistributedAuctionApp.DistributedAuctionPackage.AuctionStatus ();
    value.userID = istream.read_string ();
    value.itemName = istream.read_string ();
    value.bidPrice = istream.read_double ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DistributedAuctionApp.DistributedAuctionPackage.AuctionStatus value)
  {
    ostream.write_string (value.userID);
    ostream.write_string (value.itemName);
    ostream.write_double (value.bidPrice);
  }

}
