package DistributedAuctionApp.DistributedAuctionPackage;


/**
* DistributedAuctionApp/DistributedAuctionPackage/AuctionStatus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedAuctionApp.idl
* Sunday, March 11, 2018 9:34:59 PM CDT
*/

public final class AuctionStatus implements org.omg.CORBA.portable.IDLEntity
{
  public String userID = null;
  public String itemName = null;
  public double bidPrice = (double)0;

  public AuctionStatus ()
  {
  } // ctor

  public AuctionStatus (String _userID, String _itemName, double _bidPrice)
  {
    userID = _userID;
    itemName = _itemName;
    bidPrice = _bidPrice;
  } // ctor

} // class AuctionStatus
