package DistributedAuctionApp.DistributedAuctionPackage;

/**
* DistributedAuctionApp/DistributedAuctionPackage/IncorrectStatusExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedAuctionApp.idl
* Sunday, March 11, 2018 9:34:59 PM CDT
*/

public final class IncorrectStatusExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public DistributedAuctionApp.DistributedAuctionPackage.IncorrectStatusException value = null;

  public IncorrectStatusExceptionHolder ()
  {
  }

  public IncorrectStatusExceptionHolder (DistributedAuctionApp.DistributedAuctionPackage.IncorrectStatusException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DistributedAuctionApp.DistributedAuctionPackage.IncorrectStatusExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DistributedAuctionApp.DistributedAuctionPackage.IncorrectStatusExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DistributedAuctionApp.DistributedAuctionPackage.IncorrectStatusExceptionHelper.type ();
  }

}
