package DistributedAuctionApp.DistributedAuctionPackage;

/**
* DistributedAuctionApp/DistributedAuctionPackage/IncorrectBidExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedAuctionApp.idl
* Sunday, March 11, 2018 9:34:59 PM CDT
*/

public final class IncorrectBidExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public DistributedAuctionApp.DistributedAuctionPackage.IncorrectBidException value = null;

  public IncorrectBidExceptionHolder ()
  {
  }

  public IncorrectBidExceptionHolder (DistributedAuctionApp.DistributedAuctionPackage.IncorrectBidException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DistributedAuctionApp.DistributedAuctionPackage.IncorrectBidExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DistributedAuctionApp.DistributedAuctionPackage.IncorrectBidExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DistributedAuctionApp.DistributedAuctionPackage.IncorrectBidExceptionHelper.type ();
  }

}
