package DistributedAuctionApp.DistributedAuctionPackage;

/**
* DistributedAuctionApp/DistributedAuctionPackage/IncorrectOfferExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedAuctionApp.idl
* Sunday, March 11, 2018 9:34:59 PM CDT
*/

public final class IncorrectOfferExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public DistributedAuctionApp.DistributedAuctionPackage.IncorrectOfferException value = null;

  public IncorrectOfferExceptionHolder ()
  {
  }

  public IncorrectOfferExceptionHolder (DistributedAuctionApp.DistributedAuctionPackage.IncorrectOfferException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DistributedAuctionApp.DistributedAuctionPackage.IncorrectOfferExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DistributedAuctionApp.DistributedAuctionPackage.IncorrectOfferExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DistributedAuctionApp.DistributedAuctionPackage.IncorrectOfferExceptionHelper.type ();
  }

}
