package DistributedAuctionApp.DistributedAuctionPackage;


/**
* DistributedAuctionApp/DistributedAuctionPackage/IncorrectBidException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedAuctionApp.idl
* Sunday, March 11, 2018 9:34:59 PM CDT
*/

public final class IncorrectBidException extends org.omg.CORBA.UserException
{
  public String description = null;

  public IncorrectBidException ()
  {
    super(IncorrectBidExceptionHelper.id());
  } // ctor

  public IncorrectBidException (String _description)
  {
    super(IncorrectBidExceptionHelper.id());
    description = _description;
  } // ctor


  public IncorrectBidException (String $reason, String _description)
  {
    super(IncorrectBidExceptionHelper.id() + "  " + $reason);
    description = _description;
  } // ctor

} // class IncorrectBidException
