package DistributedAuctionApp.DistributedAuctionPackage;


/**
* DistributedAuctionApp/DistributedAuctionPackage/IncorrectStatusException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedAuctionApp.idl
* Sunday, March 11, 2018 9:34:59 PM CDT
*/

public final class IncorrectStatusException extends org.omg.CORBA.UserException
{
  public String description = null;

  public IncorrectStatusException ()
  {
    super(IncorrectStatusExceptionHelper.id());
  } // ctor

  public IncorrectStatusException (String _description)
  {
    super(IncorrectStatusExceptionHelper.id());
    description = _description;
  } // ctor


  public IncorrectStatusException (String $reason, String _description)
  {
    super(IncorrectStatusExceptionHelper.id() + "  " + $reason);
    description = _description;
  } // ctor

} // class IncorrectStatusException
