package DistributedAuctionApp.DistributedAuctionPackage;


/**
* DistributedAuctionApp/DistributedAuctionPackage/StatusHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedAuctionApp.idl
* Sunday, March 11, 2018 9:34:59 PM CDT
*/

abstract public class StatusHelper
{
  private static String  _id = "IDL:DistributedAuctionApp/DistributedAuction/Status:1.0";

  public static void insert (org.omg.CORBA.Any a, DistributedAuctionApp.DistributedAuctionPackage.AuctionStatus that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DistributedAuctionApp.DistributedAuctionPackage.AuctionStatus extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = DistributedAuctionApp.DistributedAuctionPackage.AuctionStatusHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (DistributedAuctionApp.DistributedAuctionPackage.StatusHelper.id (), "Status", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DistributedAuctionApp.DistributedAuctionPackage.AuctionStatus read (org.omg.CORBA.portable.InputStream istream)
  {
    DistributedAuctionApp.DistributedAuctionPackage.AuctionStatus value = null;
    value = DistributedAuctionApp.DistributedAuctionPackage.AuctionStatusHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DistributedAuctionApp.DistributedAuctionPackage.AuctionStatus value)
  {
    DistributedAuctionApp.DistributedAuctionPackage.AuctionStatusHelper.write (ostream, value);
  }

}
